### ISSUE TITLE
Розбити проект по папкам

### ISSUE THREAD

**Issue by lapachuka** [Stanislava15/omnifood#1]
Створи папки:
1) scripts, styles, assets i порозноси все по папкам
2) index.php - це тобі не треба ! має бути тільки index.html і всі підключенні файли до нього, все інше видаляй

**Comment by Stanislava15** [comment]
По папкам проект розбила =)

**Comment by lapachuka** [comment]
переймуй паки на lowercase

**Comment by Stanislava15** [comment]
done
